### ISSUE TITLE
Deep Linking

### ISSUE THREAD

**Issue by mayrenia-lee** [google-ar/WebARonARKit#16]
The ability to deep link into WebARonARKit app would be very useful.

Given a custom uri scheme, e.g, googlewebar:// and allowing the passing of URL as a parameter could reduce friction, improve onboarding experience and enable these scenarios

## Scan QR Code to WebAR experience

* User scans a QR Code that has a uri as the content, e,g, googlewebar://url/https://example.com/amazingar.html
* WebARonARKit app opens and loads the supplied URL

## Web page link to WebAR experience

* User clicks a link on a web page that has the custom scheme, e.g, googlewebar://url/https://example.com/mindblowingar.html
* WebARonARKit app opens and loads the supplied URL

**Comment by judax** [comment]
Sorry for the late reply. This issue will be resolved as soon as the PR number #39 is merged.

Thank you for your suggestion.

**Comment by judax** [comment]
The PR just landed! The schema to be used is webar://URL. Notice that the URL should not include the scheme (not include http://www. but just www.).
