### ISSUE TITLE
Consider enabling Geolocation with user prompt

### ISSUE THREAD

**Issue by donmccurdy** [google-ar/WebARonARKit#26]
Under *Info*, enabling `Privacy – Location When In Use...` allows JavaScript to prompt users to enable Geolocation APIs. Without this, calls to `navigator.geolocation.getCurrentPosition()` fail.

<img width="868" alt="screen shot 2017-09-23 at 4 10 53 pm" src="https://user-images.githubusercontent.com/1848368/30777878-304e6b3a-a07a-11e7-85d1-c5ff3ecf21f1.png">

Maybe this could be enabled by default in the XCode project?

**Comment by jsantell** [comment]
This sgtm as long as we still have a permissions prompt

**Comment by judax** [comment]
Should be resolved in the current master branch.

**Comment by donmccurdy** [comment]
Thanks!
