### ISSUE TITLE
CVMetalTextureRef unidentified ?

### ISSUE THREAD

**Issue by helxsz** [google-ar/WebARonARKit#33]
I am running Xcode 9 and iOS 11, but when build the project on Xcode, some errors are happening.

![screen shot 2017-11-06 at 15 21 59](https://user-images.githubusercontent.com/669670/32448306-7be5a7e4-c306-11e7-93c4-a0c9c93f4ee2.png)
![screen shot 2017-11-06 at 15 22 06](https://user-images.githubusercontent.com/669670/32448309-7d5e3172-c306-11e7-96a6-19dd602c843d.png)

Could you identify and solve the issues?

**Comment by judax** [comment]
This is very likely the same issue as: https://github.com/google-ar/WebARonARKit/issues/12

Please, verify that you are building for a final device and not for the emulators.

**Comment by helxsz** [comment]
thanks, this is right .
