### ISSUE TITLE
make an application for product?

### ISSUE THREAD

**Issue by hongmaoxiao** [google-ar/WebARonARKit#37]
**Thanks for all your great job.**<br>
I want to use this to make an application for product. But now i found the url bar is not beautiful at all.<br>
I want to know that if some function to hide that or some function in progress?<br>
In addition, can i just run the app without submit the url, when running render an example immediately?<br>
thanks.

**Comment by judax** [comment]
A quick easy fix to get rid of the URL could be to set the 
```
#define URL_TEXTFIELD_HEIGHT 0
#define PROGRESSVIEW_HEIGHT 0

```
to 0 in the ViewController.m file. If you do not want to use a remote URL you can also bundle your web app in a folder as a resource in the same XCode project and reference it with the URL being "file://FOLDER/PAGE.html". You can change the default URL
`    NSString *defaultSite = @"file://FOLDER_TO_YOUR_WEB_APP";
`
In the same ViewController.m file.

Of course, you may need to change the icon and such but, this should work.

I hope this helps.

**Comment by hongmaoxiao** [comment]
Thanks a lot.<br>
This is all I need.
