### ISSUE TITLE
iOS app rejected for use of TrueDepth API

### ISSUE THREAD

**Issue by code-matt** [google-ar/WebARonARKit#64]
I have used this and three.ar.js to make some small apps, trying my hand at AR. I have been rejected for the TrueDepth API being used without it being used in some fashion in my app. I am not much of an ObjC guy and despite my best efforts can not figure out how to turn it off in WebARonARKit. 

I see the one check about 
```ARFaceAnchor class```

However, I do not see anything in the ARSession configuration about how to disable this. Can anyone lend a hand how to do this ?

**Comment by judax** [comment]
Interesting. The project does not enable the true depth camera but it is indeed referencing the FaceAnchors in the code. I know Apple does much code analysis in their app verification process so maybe just the reference to the ARFaceAnchor type triggered their alarms somehow. I would suggest just removing that part and resubmitting it. 

Change:

        if ([anchors[i] isKindOfClass:[ARPlaneAnchor class]] ||
            [anchors[i] isKindOfClass:[ARFaceAnchor class]]) {

To:

        if ([anchors[i] isKindOfClass:[ARPlaneAnchor class]]) {

and let us know if that fixes it.

Thanks for reaching out and letting us know about this.

We are working on a major rebuild of this project so stay tuned!

**Comment by code-matt** [comment]
Thanks, I have done so and will report back here in a day or two hopefully once its reviewed again.

**Comment by code-matt** [comment]
That worked, thank you much. I never would have guessed just referencing the FaceAnchors like that triggered that failure. Looking forward to the rebuild and hope its going well!

**Comment by minenkod** [comment]
@judax I really love this repo. Any news on the rebuild?

**Comment by judax** [comment]
Sorry, this project is no longer supported. Of course, you can always fork it and continue developing it. My apologies.
