### ISSUE TITLE
Access to web-app with self-signed certificate

### ISSUE THREAD

**Issue by VioletteA** [google-ar/WebARonARKit#65]
Hi,

when I try to access to my web-application currently under development, with a self-signed SSL certificate, I get this error message. I see no option to get over it... 

_"The certificate for this server is invalid. You might be connecting to a server that is pretenting to be "my.domain.name.fr" which could put your confidential information at risk"_

Do you know how to continue navigation despite this message?

**Comment by msimpson** [comment]
@VioletteA 
A similar [question](https://github.com/google-ar/WebARonARCore/issues/19) was asked previously on the WebARonARCore side. You may want to try what @jsantell [noted regarding SSL and localhost](https://github.com/google-ar/WebARonARCore/issues/19#issuecomment-343972998).
