### ISSUE TITLE
Can't AR Hit Test

### ISSUE THREAD

**Issue by whilemouse** [google-ar/WebARonARKit#67]
Hi. thanks for created it.
I tried AR Hit Test. (https://github.com/google-ar/WebARonARKit#getting-started)
But it shown 'AR NOT FOUND' and can't demo.
How to play this demo? or Did I miss something?

Test device information
mobile: iPhoneX
os: ios 11.4.1
Xcode : 9.4.1

Test xcode information(build succeed)
![image](https://user-images.githubusercontent.com/16111790/44319813-28f5de00-a479-11e8-9964-b3d13a4277be.png)

Test WebARonARKit app
![img_be1d1105c84b-1](https://user-images.githubusercontent.com/16111790/44319862-740ff100-a479-11e8-80ef-c2268a7c7298.jpeg)

**Comment by judax** [comment]
The example you pointed to is based on WebXR and WebARonARkit is based on
WebVR 1.1 with custom menthods for AR. We are working on an update of the
project to support WebXR but cannot provide an ETA yet.

Regards,
Iker

**Comment by lincolnfrog** [comment]
Just to be clear - you can try this using current Chrome Canary and it will work. You can also develop your own AR apps on the web and test them using Chrome Canary as well: https://codelabs.developers.google.com/codelabs/ar-with-webxr/
