### ISSUE TITLE
ARC Semantic Issue

### ISSUE THREAD

**Issue by LiamChapman** [google-ar/WebARonARKit#9]
Hi there,

I downloaded the repo and tried deploying a test to my device and I get the following error:

/WebARonARKit/WebARonARKit/Renderer.m:402:48: No visible @interface for 'ARCamera' declares the selector 'projectionMatrixForOrientation:viewportSize:zNear:zFar:'

/WebARonARKit/WebARonARKit/Renderer.m:483:16: No visible @interface for 'ARFrame' declares the selector 'displayTransformForOrientation:viewportSize:'

I've tried googling and stackoverflow to try and resolve the issue and I've had no luck. 

Any suggestions?

Thanks,

Liam

**Comment by jsantell** [comment]
Just to confirm, [you're running an ARCore capable iOS device on iOS11](https://github.com/google-ar/WebARonARKit#1-install-ios-11-beta)?

**Comment by LiamChapman** [comment]
I've got iOS11 installed and i'm using Xcode Beta. It also throws errors when using a simulator too.

**Comment by rezaali** [comment]
Hi @LiamChapman thanks for reaching out! This error is probably caused by using an outdated version of iOS Beta, there has been many beta releases for both Xcode and iOS. Please let us know the exact version you are using for both and I'll investigate. 

Thanks!

**Comment by LiamChapman** [comment]
Hi @rezaali, 

I'm currently on iOS 11 Beta 3 and Xcode Beta 3. I'll update my software to the latest releases now and report back. 

Thank you.

**Comment by LiamChapman** [comment]
Hi all, 

I've just updated my iOS 11 and XCode to the latest beta and it's now deploying.

However, when I go try and example I just get a white or black screen. It's as if the camera is not enabled. I don't get a request to enable access.

After closer inspection i'm using an iPhone 6, which is not supported for ARKit. My bad.

However, I had the Apple ARKit demo working on iOS 11 Beta 3 perfectly on the iPhone 6. Seems like apple is purposely making you upgrade to get new features. Shame.

I'll have to track down an iPhone 6s or 7 to test with.

Thanks,

Liam

**Comment by judax** [comment]
Glad that you resolved the compilation error/warning.

I tried the ARKit examples when the first beta came out on my iPhone 6 and never got it working (a runtime error specified that the device did not support the AR feature). Curious on how that worked for you. A bug in one of the betas maybe?
